export const GET_TICKETS = 'GET_TICKETS';
export const FILTER_TICKETS = 'FILTER_TICKETS';
export const SWITCHING_TABS = 'SWITCHING_TABS';
export const SHOW_MORE = 'SHOW_MORE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const PUT_QUANTITY_TICKETS = 'PUT_QUANTITY_TICKETS';
export const ERROR_STATUS = 'ERROR_STATUS';
